# Generated by Django 2.0.7 on 2018-09-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='favorite_player',
            field=models.ManyToManyField(blank=True, related_name='favorite_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='favorite_games', to='website.Game'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
