# Generated by Django 2.0.7 on 2018-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180912_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
